export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string; // 'amber' | 'blue' | 'violet' | 'sky' | 'rose' | 'emerald' | 'indigo' | 'cyan' | 'orange' | 'red' | 'pink' | 'zinc'
  documents: number;
  chats: number;
  memories: number;
  storage: string;
  lastUpdated: string;
  lastUpdatedMs: number; // For sorting
  createdAt: string;
  createdAtMs: number; // For sorting
  category: string;
  isPinned: boolean;
  tags: string[];
}

export const mockSkills: Skill[] = [
  {
    id: "skill-1",
    name: "Electrical Engineering",
    description: "Manage electrical documentation, wiring diagrams, PLC manuals and cable specifications.",
    icon: "Wrench",
    color: "amber",
    documents: 42,
    chats: 86,
    memories: 132,
    storage: "1.8 GB",
    lastUpdated: "2 hours ago",
    lastUpdatedMs: Date.now() - 2 * 60 * 60 * 1000,
    createdAt: "2026-05-10",
    createdAtMs: Date.now() - 45 * 24 * 60 * 60 * 1000,
    category: "Engineering",
    isPinned: true,
    tags: ["PLC", "Wiring", "Hardware"],
  },
  {
    id: "skill-2",
    name: "Mechanical Systems",
    description: "CAD drawings, pump schematics, HVAC design specifications, and fluid dynamics manuals.",
    icon: "Settings",
    color: "blue",
    documents: 18,
    chats: 32,
    memories: 64,
    storage: "850 MB",
    lastUpdated: "5 hours ago",
    lastUpdatedMs: Date.now() - 5 * 60 * 60 * 1000,
    createdAt: "2026-06-01",
    createdAtMs: Date.now() - 25 * 24 * 60 * 60 * 1000,
    category: "Engineering",
    isPinned: true,
    tags: ["CAD", "HVAC", "Fluidics"],
  },
  {
    id: "skill-3",
    name: "SAP Integration",
    description: "API endpoints, data mapping tables, and authentication protocols for enterprise SAP syncing.",
    icon: "Database",
    color: "violet",
    documents: 32,
    chats: 12,
    memories: 45,
    storage: "2.1 GB",
    lastUpdated: "1 day ago",
    lastUpdatedMs: Date.now() - 24 * 60 * 60 * 1000,
    createdAt: "2026-04-15",
    createdAtMs: Date.now() - 70 * 24 * 60 * 60 * 1000,
    category: "Enterprise",
    isPinned: true,
    tags: ["SAP", "API", "Sync"],
  },
  {
    id: "skill-4",
    name: "React Docs & Standards",
    description: "Custom hook implementation patterns, frontend performance audit checklists, and core UI components.",
    icon: "Code",
    color: "sky",
    documents: 56,
    chats: 210,
    memories: 312,
    storage: "420 MB",
    lastUpdated: "15 minutes ago",
    lastUpdatedMs: Date.now() - 15 * 60 * 1000,
    createdAt: "2026-06-20",
    createdAtMs: Date.now() - 6 * 24 * 60 * 60 * 1000,
    category: "Development",
    isPinned: false,
    tags: ["React", "UI/UX", "Best Practices"],
  },
  {
    id: "skill-5",
    name: "Machine Learning Models",
    description: "Neural network training configs, parameter settings, weights validation, and data pipelines.",
    icon: "Brain",
    color: "rose",
    documents: 89,
    chats: 412,
    memories: 812,
    storage: "6.4 GB",
    lastUpdated: "3 hours ago",
    lastUpdatedMs: Date.now() - 3 * 60 * 60 * 1000,
    createdAt: "2026-03-10",
    createdAtMs: Date.now() - 105 * 24 * 60 * 60 * 1000,
    category: "AI & ML",
    isPinned: false,
    tags: ["PyTorch", "Weights", "Pipelines"],
  },
  {
    id: "skill-6",
    name: "PLC Automation Systems",
    description: "Logic controllers logic documentation, ladder diagrams, and Siemens S7 configurations.",
    icon: "Cpu",
    color: "emerald",
    documents: 24,
    chats: 115,
    memories: 88,
    storage: "1.2 GB",
    lastUpdated: "4 days ago",
    lastUpdatedMs: Date.now() - 4 * 24 * 60 * 60 * 1000,
    createdAt: "2026-05-25",
    createdAtMs: Date.now() - 30 * 24 * 60 * 60 * 1000,
    category: "Engineering",
    isPinned: false,
    tags: ["Siemens", "Automation", "S7"],
  },
  {
    id: "skill-7",
    name: "Cloud Computing & AWS",
    description: "Infrastructure as Code policies, IAM roles, cloud network routing, and EC2 scaling logs.",
    icon: "Cloud",
    color: "indigo",
    documents: 67,
    chats: 98,
    memories: 140,
    storage: "3.7 GB",
    lastUpdated: "Yesterday",
    lastUpdatedMs: Date.now() - 26 * 60 * 60 * 1000,
    createdAt: "2026-05-01",
    createdAtMs: Date.now() - 55 * 24 * 60 * 60 * 1000,
    category: "Infrastructure",
    isPinned: false,
    tags: ["AWS", "IaC", "Security"],
  },
  {
    id: "skill-8",
    name: "Network Infrastructure",
    description: "Firewall rules, routing tables, VPN client certificates, and switch interface templates.",
    icon: "Network",
    color: "cyan",
    documents: 15,
    chats: 45,
    memories: 62,
    storage: "520 MB",
    lastUpdated: "3 days ago",
    lastUpdatedMs: Date.now() - 3 * 24 * 60 * 60 * 1000,
    createdAt: "2026-06-10",
    createdAtMs: Date.now() - 16 * 24 * 60 * 60 * 1000,
    category: "Infrastructure",
    isPinned: false,
    tags: ["VPN", "Routing", "Firewall"],
  },
  {
    id: "skill-9",
    name: "Project Alpha specifications",
    description: "Strictly confidential product roadmap, stakeholder interview transcripts, and launch deliverables.",
    icon: "Folder",
    color: "orange",
    documents: 145,
    chats: 892,
    memories: 1205,
    storage: "12.8 GB",
    lastUpdated: "2 days ago",
    lastUpdatedMs: Date.now() - 2 * 24 * 60 * 60 * 1000,
    createdAt: "2026-01-15",
    createdAtMs: Date.now() - 160 * 24 * 60 * 60 * 1000,
    category: "Projects",
    isPinned: false,
    tags: ["Roadmap", "Confidential", "Launch"],
  },
  {
    id: "skill-10",
    name: "Project Phoenix blueprint",
    description: "Phoenix system architecture diagrams, database schema refactors, and fallback plans.",
    icon: "Flame",
    color: "red",
    documents: 98,
    chats: 342,
    memories: 512,
    storage: "8.2 GB",
    lastUpdated: "1 week ago",
    lastUpdatedMs: Date.now() - 7 * 24 * 60 * 60 * 1000,
    createdAt: "2026-02-28",
    createdAtMs: Date.now() - 116 * 24 * 60 * 60 * 1000,
    category: "Projects",
    isPinned: false,
    tags: ["Refactor", "Schema", "Migration"],
  },
  {
    id: "skill-11",
    name: "AI & LLM Research Notes",
    description: "Embeddings validation models, temperature tuning benchmarks, and agent prompt templates.",
    icon: "Sparkles",
    color: "pink",
    documents: 73,
    chats: 289,
    memories: 442,
    storage: "4.1 GB",
    lastUpdated: "6 hours ago",
    lastUpdatedMs: Date.now() - 6 * 60 * 60 * 1000,
    createdAt: "2026-04-01",
    createdAtMs: Date.now() - 85 * 24 * 60 * 60 * 1000,
    category: "AI & ML",
    isPinned: false,
    tags: ["Embeddings", "Prompts", "Tuning"],
  },
  {
    id: "skill-12",
    name: "Technical Documentation Hub",
    description: "Standard operating procedures, disaster recovery runbooks, and internal onboarding guidebooks.",
    icon: "FileText",
    color: "zinc",
    documents: 112,
    chats: 156,
    memories: 232,
    storage: "2.9 GB",
    lastUpdated: "5 days ago",
    lastUpdatedMs: Date.now() - 5 * 24 * 60 * 60 * 1000,
    createdAt: "2026-05-12",
    createdAtMs: Date.now() - 44 * 24 * 60 * 60 * 1000,
    category: "Documentation",
    isPinned: false,
    tags: ["SOP", "Onboarding", "Runbooks"],
  },
];

export const mockCategories = [
  "All",
  "Engineering",
  "Development",
  "Enterprise",
  "Infrastructure",
  "Projects",
  "AI & ML",
  "Documentation",
];
